<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	
	<!-- Base Box -->
    <xacro:property name="base_name" value="chassis"/>
    <xacro:property name="base_box_mass" value="1.0"/>
	<xacro:property name="base_box_x" value="0.1"/>
    <xacro:property name="base_box_y" value="0.1"/>
    <xacro:property name="base_box_z" value="0.1"/>

    <!-- Wheels -->
	<xacro:property name="wheel_radius" value="${base_box_z / 4.0}"/>
    <xacro:property name="wheel_width" value="0.001"/>
    <xacro:property name="wheel_increment" value="0.010"/>
    <xacro:property name="mu1_wheel" value="0.5"/>
    <xacro:property name="mu2_wheel" value="0.5"/>
    <xacro:property name="kp_wheel" value="1000.0"/>
    <xacro:property name="kd_wheel" value="1000.0"/>

    <!--Caster Wheels-->
    <xacro:property name="dummy_length" value="0.001"/>

</robot>
